"""add_parent_message_id_to_messages

Revision ID: 3b22ddb2e5e9
Revises: d37c4ed6ea05
Create Date: 2026-07-14 14:21:44.863525+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b22ddb2e5e9'
down_revision: Union[str, None] = 'd37c4ed6ea05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
