"""add_parent_message_id_to_messages

Revision ID: d37c4ed6ea05
Revises: 0001
Create Date: 2026-07-14 13:58:29.744027+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37c4ed6ea05'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###
