import { DEFAULT_PLATFORM, type Topic, type WorkflowConfig } from "@/types/workflow";

export const supportedPlatforms = [
  {
    id: DEFAULT_PLATFORM,
    label: "知乎",
  },
] as const;

export const defaultPlatform = supportedPlatforms[0].id;

export const fallbackTopics: Topic[] = [
  {
    id: "algo",
    name: "数据结构与算法",
    keywords: ["数据结构", "算法", "二叉树", "链表", "动态规划", "leetcode"],
    expandedHints: [
      "数据结构与算法",
      "数据结构",
      "算法",
      "二叉树",
      "链表",
      "动态规划",
      "leetcode",
      "结构",
      "栈",
      "队列",
      "哈希",
      "哈希表",
      "堆",
      "图",
      "并查集",
      "dp",
      "回溯",
      "贪心",
      "递归",
      "排序",
      "查找",
      "时间复杂度",
      "空间复杂度",
      "复杂度",
      "刷题",
      "面试算法",
    ],
  },
  {
    id: "personal-site",
    name: "个人站点",
    keywords: ["个人站点", "独立站", "博客", "建站", "个人主页"],
    expandedHints: [
      "个人站点",
      "独立站",
      "博客",
      "建站",
      "个人主页",
      "个人网站",
      "独立博客",
      "主页",
      "网站设计",
      "网页设计",
      "作品集网站",
      "portfolio",
      "导航页",
      "展示页",
      "站点推荐",
      "网站推荐",
      "站点展示",
      "好看的网站",
      "好看的个人网站",
      "好看的个人站点",
      "网站审美",
      "网站案例",
      "个人品牌网站",
      "开发者主页",
      "十年前做个人网站",
      "大家的个人网站",
      "有多少人有自己的个人网站",
    ],
  },
  {
    id: "podcast",
    name: "播客",
    keywords: ["播客", "podcast", "音频节目", "内容创作"],
    expandedHints: ["播客", "podcast", "音频节目", "内容创作", "播客推荐", "播客创作", "做播客", "独立播客"],
  },
];

export const fallbackWorkflow: WorkflowConfig = {
  platform: defaultPlatform,
  maxPushCount: 10,
  sortModes: ["latest", "answer_count"],
  answerStyle: "像一个长期观察现实问题的人在认真表达判断，语言自然，有事实感、故事感和经历感，不要模板化，不要AI腔",
  systemPrompt:
    "你输出的内容必须是中文 Markdown 正文，不要包裹 JSON。\n不要使用明显的AI套话，例如下面我将、首先我们来分析、综上所述等过强模板语言。\n回答要像一个真正有判断力的人在写，而不是像机器在拼装结构。\n优先让内容自然、可信、有人味，其次才是结构完整。\n绝对不要编造模糊的个人经历来撑内容。\n如果写案例，必须交代清楚因果链条；如果做不到，就直接讲事实和判断，不要硬凑故事。\n禁止输出空泛正确但没有信息量的句子。\n如果一句话放进任何主题里都成立，那它大概率太空，应该重写得更具体。",
  testMode: true,
  skipAnswerGeneration: false,
  userAgent: "",
  ctaText: "",
  outputDir: "",
};
