from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import Task, TaskLease


class TaskHandler(Protocol):
    async def handle(self, task: Task) -> None:
        """执行一个具体业务任务。"""
        ...


class TaskQueue(Protocol):
    """任务存储端口；数据库、Redis 和内存队列实现相同生命周期语义。"""

    async def start(self) -> None: ...

    async def submit(self, task: Task) -> None: ...

    async def claim(self, owner: str, lease_seconds: float) -> TaskLease | None: ...

    async def renew(self, lease: TaskLease, lease_seconds: float) -> TaskLease: ...

    async def complete(self, lease: TaskLease) -> None: ...

    async def retry(self, lease: TaskLease, error: str, retry_at: datetime) -> None: ...

    async def fail(self, lease: TaskLease, error: str) -> None: ...

    async def release(self, lease: TaskLease) -> None: ...

    async def recover_stale(self, now: datetime) -> int: ...

    async def close(self) -> None: ...


class TaskNotifier(Protocol):
    """新任务通知端口；generation 用于避免 clear/set 竞态丢失通知。"""

    @property
    def generation(self) -> int: ...

    async def start(self) -> None: ...

    async def notify(self) -> None: ...

    async def wait(self, after_generation: int, timeout: float) -> None: ...

    async def close(self) -> None: ...
